#!/usr/bin/env bash

name="sandbox"
tv_ip="x.x.x.x"

if [[ -f ./$name ]]; then
	rm ./$name
fi

# Libraries from soc_lib
libs="-lapp-mgr "
libs+="-lfpp "
#libs+="-lasound "
#libs+="-lcares "
#libs+="-lcomedia "
libs+="-lcrypt_ntk "
#libs+="-lcrypto "
#libs+="-lcurl "
#libs+="-ldirect "
#libs+="-ldirectfb "
#libs+="-ldl "
#libs+="-ldsmcc_stack "
#libs+="-lEGL "
#libs+="-lexpat "
#libs+="-lfribidi "
#libs+="-lpthread "
#libs+="-lfusion "
#libs+="-lGenIPCSocket "
#libs+="-lGLESv1_CM "
#libs+="-lGLESv2 "
#libs+="-lhbbtvmsg "
libs+="-lhdcp2_platform "
libs+="-lhdcp_ntk "
#libs+="-liconv "
#libs+="-ljpeg "
#libs+="-ljson "
#libs+="-lm "
#libs+="-lMali "
#libs+="-lmiracast_client "
#libs+="-lnewportal "
libs+="-lnteec "
#libs+="-lpng "
#libs+="-lqrencode "
#libs+="-lrt "
#libs+="-lsawman "
#libs+="-lscew "
#libs+="-lsqlite3 "
#libs+="-lssl "
#libs+="-ltable "
libs+="-ltcl_dlna "
libs+="-ltcl_pbi "
#libs+="-ltinyxml "
#libs+="-lUMP "
#libs+="-lwfd "
libs+="-lwotv "
#libs+="-lxml2 "
libs+="-lz "

arm-linux-gnueabihf-gcc -Wno-implicit-function-declaration --std=gnu99 -o $name ./main.c -L ../tcl_libs $libs
ssh root@$tv_ip "killall -s KILL $name 2>/dev/null"
cat ./$name | ssh root@$tv_ip "cat > /tmp/$name"
ssh root@$tv_ip "chmod +x /tmp/$name"
