//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2018 Retargetable Decompiler <info@retdec.com>
//

#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// ------------------- Function Prototypes --------------------

int32_t cleanup_module(void);
int32_t function_1f28(void);
int32_t kteec_add_service(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7);
int32_t kteec_close_session_of_service(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13, int32_t a14, int32_t (*a15)(int32_t), int32_t a16, int32_t a17, int32_t a18, int32_t a19, int32_t a20, int32_t a21, int32_t a22);
int32_t kteec_do_secure_call(int32_t * a1);
int32_t kteec_exit(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5);
int32_t kteec_get_revision(int32_t a1, int32_t a2);
int32_t kteec_init(int32_t a1);
int32_t kteec_invoke_command(int32_t a1, uint32_t a2);
int32_t kteec_ioctl(int32_t a1, int32_t a2, uint32_t a3, int32_t a4);
int32_t kteec_mmap(int32_t a1);
int32_t kteec_open(int32_t a1, int32_t a2);
int32_t kteec_release(int32_t a1);
int32_t kteec_service_task(int32_t a1, int32_t a2);
int32_t kteec_wsm_alloc(uint32_t a1);
int32_t kteec_wsm_free(int32_t a1);
int32_t kteec_wsm_init(int32_t * a1, uint32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13, int32_t a14, int32_t a15);
int32_t link_2_next_free_block(int32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t next_free_block(int32_t a1, int32_t a2, int32_t a3);
int32_t size_of_block(int32_t a1, int32_t a2, int32_t a3);
int32_t unknown_3600(void);
int32_t unknown_384c(void);

// --------------------- Global Variables ---------------------

int32_t g1 = 0; // LR
int32_t g2 = 0; // R0
int32_t g3 = 0; // R1
int32_t g4 = 0; // R10
int32_t g5 = 0; // R11
int32_t g6 = 0; // R12
int32_t g7 = 0; // R2
int32_t g8 = 0; // R3
int32_t g9 = 0; // R4
int32_t g10 = 0; // R5
int32_t g11 = 0; // R6
int32_t g12 = 0; // R7
int32_t g13 = 0; // R8
int32_t g14 = 0; // R9

// ------------------------ Functions -------------------------

// Address range: 0x0 - 0x2f
int32_t kteec_do_secure_call(int32_t * a1) {
    int32_t v1 = (int32_t)a1;
    int32_t v2 = g6;
    int32_t v3 = g1;
    g1 = 20;
    g6 = v1;
    g2 = 1;
    g3 = *a1;
    int32_t v4 = *(int32_t *)(v1 + 4);
    g7 = v4;
    int32_t v5 = *(int32_t *)(v1 + 8);
    g8 = v5;
    *(int32_t *)(v1 + 12) = 1;
    *(int32_t *)(g6 + 16) = g3;
    g5 = v3;
    ((int32_t (*)(int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t))v2)(1, g3, v4, v5, v2, v3, 12);
    return 1;
}

// Address range: 0x30 - 0x1eb
int32_t kteec_close_session_of_service(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13, int32_t a14, int32_t (*a15)(int32_t), int32_t a16, int32_t a17, int32_t a18, int32_t a19, int32_t a20, int32_t a21, int32_t a22) {
    int32_t v1 = g5; // bp+34
    int32_t v2 = *(int32_t *)(v1 + 8); // bp+64
    g10 = v2;
    g11 = *(int32_t *)(v1 + 12);
    int32_t v3 = *(int32_t *)(v1 + 16); // bp+64
    g12 = v3;
    g14 = *(int32_t *)(v1 + 24);
    g4 = *(int32_t *)(v1 + 28);
    g5 = *(int32_t *)(v1 + 32);
    int32_t result = *(int32_t *)480; // bp+68
    g13 = result;
    g1 = 116;
    int32_t v4 = result + 96; // bp+78
    int32_t v5 = *(int32_t *)v4; // bp+78
    g9 = v5;
    if (v5 == v4) {
        // 0x84
        mutex_unlock();
        return result;
    }
    while (true) {
        // 0x94
        if (*(int32_t *)(v5 + 8) == v2) {
            int32_t v6 = *(int32_t *)484;
            g14 = v6;
            *(int32_t *)v3 = v2;
            *(int32_t *)(v3 + 8) = *(int32_t *)v6;
            *(int32_t *)(v3 + 12) = *(int32_t *)(v6 + 4);
            *(int32_t *)(v3 + 16) = *(int32_t *)(v6 + 8);
            *(int32_t *)(v3 + 20) = *(int32_t *)(v6 + 12);
            *(int32_t *)(g12 + 24) = 2;
            int32_t v7 = *(int32_t *)(g4 + 8);
            *(int32_t *)(g12 + 32) = *(int32_t *)(v7 + 4);
            *(int32_t *)(g12 + 28) = *(int32_t *)v7;
            *(int32_t *)(g12 + 40) = *(int32_t *)(v7 + 12);
            *(int32_t *)(g12 + 36) = *(int32_t *)(v7 + 8);
            int32_t v8 = g13;
            int32_t v9 = *(int32_t *)(v8 + 108);
            int32_t v10 = *(int32_t *)(v8 + 104); // bp+108
            *(int32_t *)(g9 + 76) = 1;
            *(int32_t *)(g9 + 80) = v10 + *(int32_t *)(v8 + 124) - v9;
            if (g9 != -60) {
                // 0x1cc
                // branch -> 0x13c
            }
            int32_t v11 = g11 + 16; // bp+140
            g12 = v11;
            int32_t v12 = *(int32_t *)v11; // bp+148
            if (v11 != v12) {
                int32_t v13 = *(int32_t *)v12; // bp+154
                int32_t v14 = v13; // R3
                int32_t v15 = v12 - 8; // bp+160
                g9 = v15;
                g4 = 0x100100;
                g13 = 0x200200;
                g10 = v13 - 8;
                // branch -> 0x170
                while (true) {
                    int32_t v16 = *(int32_t *)(v15 + 12); // bp+170
                    *(int32_t *)(v13 + 4) = v16;
                    *(int32_t *)v16 = v14;
                    int32_t v17 = g9;
                    int32_t v18 = *(int32_t *)(v17 + 20);
                    *(int32_t *)(v17 + 8) = g4;
                    *(int32_t *)(g9 + 12) = g13;
                    if (v18 != 0) {
                        // 0x190
                        kteec_wsm_free(v18);
                        // branch -> 0x194
                    }
                    int32_t v19 = g10; // bp+198
                    g9 = v19;
                    int32_t v20 = v19 + 8;
                    int32_t v21 = *(int32_t *)v20;
                    v14 = v21;
                    g10 = v21 - 8;
                    if (g12 == v20) {
                        // break -> 0x1b4
                        break;
                    }
                    v13 = v21;
                    v15 = v19;
                    // continue -> 0x170
                }
                // 0x1b4
                // branch -> 0x1b8
            }
            while (true) {
                // 0x1b8
                // branch -> 0x1b8
            }
        } else {
            int32_t v22 = *(int32_t *)v5; // bp+88
            g9 = v22;
            if (v22 == v4) {
                // break -> 0x1c4
                break;
            }
            v5 = v22;
            // continue -> 0x94
            continue;
        }
    }
    while (true) {
        // 0x1c4
        // branch -> 0x1c4
    }
}

// Address range: 0x1ec - 0x43f
int32_t kteec_release(int32_t a1) {
    int32_t v1 = 504; // bp-4
    g5 = &v1;
    g4 = g3;
    int32_t v2 = *(int32_t *)(g3 + 124);
    int32_t v3 = *(int32_t *)1084 + 96; // bp+218
    int32_t v4 = *(int32_t *)v3; // bp+218
    int32_t v5 = *(int32_t *)v4; // bp+220
    g13 = v5;
    if (v4 != v3) {
        // 0x228
        int32_t * v6;
        int32_t v7; // R0
        int32_t v8;
        int32_t v9; // bp+374
        int32_t v10;
        int32_t v11;
        int32_t v12; // bp+380
        int32_t v13;
        int32_t v14;
        int32_t v15;
        int32_t v16;
        int32_t v17; // bp+380
        int32_t v18;
        int32_t v19;
        int32_t v20;
        if (*(int32_t *)(v4 + 8) == v2) {
            // 0x268
            g13 = v4;
            // branch -> 0x26c
        } else {
            // 0x248
            if (v5 != v3) {
                int32_t v21 = v5; // bp+238
                int32_t v22 = *(int32_t *)v5; // bp+244
                while (true) {
                    // 0x238
                    if (*(int32_t *)(v21 + 8) == v2) {
                        v4 = v21;
                        // 0x26c
                        v8 = v4 + 16;
                        g1 = 636;
                        v15 = *(int32_t *)v8;
                        g9 = v15;
                        if (v8 != v15) {
                            // 0x28c
                            g12 = 0x100100;
                            g11 = 0x200200;
                            g13 = *(int32_t *)v15;
                            v10 = v15;
                            // branch -> 0x2a8
                            while (true) {
                                // 0x2a8
                                v14 = v10 + 12;
                                v16 = *(int32_t *)v14;
                                v7 = v16;
                                g10 = v14;
                                v11 = v10;
                                int32_t v23;
                                int32_t v24;
                                int32_t v25;
                                if (v14 != v16) {
                                  lab_if_2b4_0_true:;
                                    int32_t v26 = *(int32_t *)v16;
                                    g14 = v26;
                                    int32_t v27 = *(int32_t *)(v16 + 4);
                                    *(int32_t *)(v26 + 4) = v27;
                                    *(int32_t *)v27 = g14;
                                    *(int32_t *)v7 = g12;
                                    *(int32_t *)(v7 + 4) = g11;
                                    int32_t v28 = *(int32_t *)(g4 + 124);
                                    int32_t v29;
                                    kteec_close_session_of_service(v28, v10, v16, v27, v29, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0, 0, 0, 0, 0, 0, 0);
                                    int32_t v30 = g14;
                                    v7 = v30;
                                    int32_t v31 = *(int32_t *)v30;
                                    g14 = v31;
                                    int32_t v32 = g9;
                                    v11 = v32;
                                    // branch -> 0x2bc
                                    while (g10 != v30) {
                                        // 0x2bc
                                        v16 = v30;
                                        v27 = *(int32_t *)(v16 + 4);
                                        *(int32_t *)(v31 + 4) = v27;
                                        *(int32_t *)v27 = g14;
                                        *(int32_t *)v7 = g12;
                                        *(int32_t *)(v7 + 4) = g11;
                                        v28 = *(int32_t *)(g4 + 124);
                                        kteec_close_session_of_service(v28, v32, v16, v27, v29, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0, 0, 0, 0, 0, 0, 0);
                                        v30 = g14;
                                        v7 = v30;
                                        v31 = *(int32_t *)v30;
                                        g14 = v31;
                                        v32 = g9;
                                        v11 = v32;
                                        // continue -> 0x2bc
                                    }
                                    // 0x2f0
                                    v24 = *(int32_t *)(v11 + 4);
                                    v25 = *(int32_t *)v11;
                                    *(int32_t *)(v25 + 4) = v24;
                                    *(int32_t *)v24 = v25;
                                    *(int32_t *)g9 = g12;
                                    *(int32_t *)(g9 + 4) = g11;
                                    v23 = g13;
                                    g9 = v23;
                                    g1 = 788;
                                    g13 = *(int32_t *)v23;
                                    if (v8 == v23) {
                                        // break -> 0x324
                                        break;
                                    }
                                    v10 = v23;
                                    // continue -> 0x2a8
                                    continue;
                                }
                              lab_0x2f0:
                                // 0x2f0
                                v24 = *(int32_t *)(v11 + 4);
                                v25 = *(int32_t *)v11;
                                *(int32_t *)(v25 + 4) = v24;
                                *(int32_t *)v24 = v25;
                                *(int32_t *)g9 = g12;
                                *(int32_t *)(g9 + 4) = g11;
                                v23 = g13;
                                g9 = v23;
                                g1 = 788;
                                g13 = *(int32_t *)v23;
                                if (v8 == v23) {
                                    // break -> 0x324
                                    break;
                                }
                                v10 = v23;
                                // continue -> 0x2a8
                            }
                            // 0x324
                            g13 = v4;
                            // branch -> 0x328
                        }
                        // 0x328
                        v6 = (int32_t *)(v4 + 36);
                        v12 = v4;
                        if (*v6 != 0) {
                            // 0x334
                            if ((*(int32_t *)(v4 + 40) & 2) == 0) {
                                while (true) {
                                    // 0x35c
                                    // branch -> 0x35c
                                }
                            } else {
                                // 0x368
                                *v6 = 0;
                                v12 = g13;
                                // branch -> 0x370
                                // 0x370
                                g4 = v12 + 96;
                                v9 = v12 + 28;
                                g10 = v9;
                                v17 = *(int32_t *)v9;
                                g9 = v17;
                                if (v9 != v17) {
                                    // 0x38c
                                    v18 = *(int32_t *)v17;
                                    g14 = v18;
                                    g12 = 0x100100;
                                    g11 = 0x200200;
                                    int32_t v33 = v18;
                                    int32_t v34 = v17;
                                    // branch -> 0x3a0
                                    while (true) {
                                        // 0x3a0
                                        v19 = *(int32_t *)(v34 + 4);
                                        *(int32_t *)(v33 + 4) = v19;
                                        *(int32_t *)v19 = g14;
                                        v13 = g9;
                                        v20 = *(int32_t *)(v13 + 20);
                                        *(int32_t *)v13 = g12;
                                        *(int32_t *)(g9 + 4) = g11;
                                        if (v20 != 0) {
                                          lab_0x3c0_3:
                                            // 0x3c0
                                            kteec_wsm_free(v20);
                                            // branch -> 0x3c4
                                        }
                                      lab_0x3c4_3:;
                                        int32_t v35 = g9;
                                        int32_t v36 = g14;
                                        g9 = v36;
                                        if (v35 == 0) {
                                            int32_t v37 = *(int32_t *)v36;
                                            g14 = v37;
                                            if (g10 == v36) {
                                                // break -> 0x3e4
                                                break;
                                            }
                                            v33 = v37;
                                            v34 = v36;
                                            // continue -> 0x3a0
                                            continue;
                                        } else {
                                            while (true) {
                                                // 0x3d4
                                                // branch -> 0x3d4
                                            }
                                            // 0x3e4
                                            // branch -> 0x3e8
                                            while (true) {
                                                // 0x3e8
                                                // branch -> 0x3e8
                                            }
                                        }
                                    }
                                }
                                while (true) {
                                    // 0x3e8
                                    // branch -> 0x3e8
                                }
                            }
                        }
                        // 0x370
                        g4 = v12 + 96;
                        v9 = v12 + 28;
                        g10 = v9;
                        v17 = *(int32_t *)v9;
                        g9 = v17;
                        if (v9 != v17) {
                            // 0x38c
                            v18 = *(int32_t *)v17;
                            g14 = v18;
                            g12 = 0x100100;
                            g11 = 0x200200;
                            // branch -> 0x3a0
                            while (true) {
                                // 0x3a0
                                v19 = *(int32_t *)(v17 + 4);
                                *(int32_t *)(v18 + 4) = v19;
                                *(int32_t *)v19 = g14;
                                v13 = g9;
                                v20 = *(int32_t *)(v13 + 20);
                                *(int32_t *)v13 = g12;
                                *(int32_t *)(g9 + 4) = g11;
                                if (v20 == 0) {
                                    goto lab_0x3c4_3;
                                }
                                goto lab_0x3c0_3;
                            }
                        }
                        while (true) {
                            // 0x3e8
                            // branch -> 0x3e8
                        }
                    } else {
                        // 0x244
                        g13 = v22;
                        if (v22 == v3) {
                            // break -> 0x254
                            break;
                        }
                        v21 = v22;
                        v22 = *(int32_t *)v22;
                        // continue -> 0x238
                        continue;
                    }
                }
                // 0x254
                // branch -> 0x258
                while (true) {
                    // 0x258
                    // branch -> 0x258
                }
            }
            // 0x254
            // branch -> 0x258
            while (true) {
                // 0x258
                // branch -> 0x258
            }
        }
        // 0x26c
        v8 = v4 + 16;
        g1 = 636;
        v15 = *(int32_t *)v8;
        g9 = v15;
        if (v8 != v15) {
            // 0x28c
            g12 = 0x100100;
            g11 = 0x200200;
            g13 = *(int32_t *)v15;
            v10 = v15;
            // branch -> 0x2a8
            while (true) {
                // 0x2a8
                v14 = v10 + 12;
                v16 = *(int32_t *)v14;
                v7 = v16;
                g10 = v14;
                if (v14 == v16) {
                    v11 = v10;
                    goto lab_0x2f0;
                }
                goto lab_if_2b4_0_true;
            }
        }
        // 0x328
        v6 = (int32_t *)(v4 + 36);
        v12 = v4;
        if (*v6 != 0) {
            // 0x334
            if ((*(int32_t *)(v4 + 40) & 2) == 0) {
                while (true) {
                    // 0x35c
                    // branch -> 0x35c
                }
            } else {
                // 0x368
                *v6 = 0;
                v12 = g13;
                // branch -> 0x370
                // 0x370
                g4 = v12 + 96;
                v9 = v12 + 28;
                g10 = v9;
                v17 = *(int32_t *)v9;
                g9 = v17;
                if (v9 != v17) {
                    // 0x38c
                    v18 = *(int32_t *)v17;
                    g14 = v18;
                    g12 = 0x100100;
                    g11 = 0x200200;
                    // branch -> 0x3a0
                    while (true) {
                        // 0x3a0
                        v19 = *(int32_t *)(v17 + 4);
                        *(int32_t *)(v18 + 4) = v19;
                        *(int32_t *)v19 = g14;
                        v13 = g9;
                        v20 = *(int32_t *)(v13 + 20);
                        *(int32_t *)v13 = g12;
                        *(int32_t *)(g9 + 4) = g11;
                        if (v20 == 0) {
                            goto lab_0x3c4_3;
                        }
                        goto lab_0x3c0_3;
                    }
                }
                while (true) {
                    // 0x3e8
                    // branch -> 0x3e8
                }
            }
        }
        // 0x370
        g4 = v12 + 96;
        v9 = v12 + 28;
        g10 = v9;
        v17 = *(int32_t *)v9;
        g9 = v17;
        if (v9 != v17) {
            // 0x38c
            v18 = *(int32_t *)v17;
            g14 = v18;
            g12 = 0x100100;
            g11 = 0x200200;
            // branch -> 0x3a0
            while (true) {
                // 0x3a0
                v19 = *(int32_t *)(v17 + 4);
                *(int32_t *)(v18 + 4) = v19;
                *(int32_t *)v19 = g14;
                v13 = g9;
                v20 = *(int32_t *)(v13 + 20);
                *(int32_t *)v13 = g12;
                *(int32_t *)(g9 + 4) = g11;
                if (v20 == 0) {
                    goto lab_0x3c4_3;
                }
                goto lab_0x3c0_3;
            }
        }
        while (true) {
            // 0x3e8
            // branch -> 0x3e8
        }
    }
    while (true) {
        // 0x258
        // branch -> 0x258
    }
}

// Address range: 0x440 - 0x4e3
int32_t kteec_add_service(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7) {
    int32_t v1 = g9; // bp+444
    int32_t v2 = g10; // bp+444
    int32_t v3 = g11; // bp+444
    int32_t v4 = g1;
    int32_t v5 = *(int32_t *)(*(int32_t *)1240 + 24); // bp+460
    int32_t v6 = 16;
    int32_t v7 = a2; // bp+484
    if (v5 != 0) {
        // 0x46c
        v6 = v5;
        v7 = a2;
        // branch -> 0x480
    }
    while (true) {
        int32_t v8 = v6; // R4
        *(int32_t *)(v6 + 8) = v7;
        int32_t v9 = *(int32_t *)1244; // bp+488
        g3 = v9;
        g1 = 1172;
        int32_t v10 = v8 + 12; // bp+494
        g7 = a1 + 16;
        *(int32_t *)v10 = v10;
        g2 = 0;
        *(int32_t *)(v8 + 16) = v10;
        int32_t * v11 = (int32_t *)(a1 + 20);
        int32_t v12 = *v11; // R3
        *v11 = v8;
        int32_t v13 = v8;
        *(int32_t *)v13 = g7;
        *(int32_t *)(v13 + 4) = v12;
        *(int32_t *)v12 = v8;
        int32_t * v14 = (int32_t *)(a1 + 12);
        *v14 = *v14 + 1;
        g8 = v4;
        g9 = a4;
        g10 = v1;
        g11 = v2;
        g5 = v3;
        ((int32_t (*)(int32_t, int32_t, int32_t, int32_t))g6)(0, v9, g7, v4);
        v6 = 16;
        v7 = g11;
        // branch -> 0x480
    }
}

// Address range: 0x4e4 - 0x6a7
int32_t kteec_open(int32_t a1, int32_t a2) {
    int32_t v1 = *(int32_t *)(*(int32_t *)1664 + 28); // bp+504
    int32_t v2 = 16;
    if (v1 != 0) {
        // 0x510
        v2 = v1;
        // branch -> 0x524
    }
    int32_t v3 = *(int32_t *)1668; // bp+524
    int32_t v4 = 0; // R6
    int32_t * v5 = (int32_t *)(v3 + 88);
    *v5 = *v5 + 1;
    int32_t v6 = *(int32_t *)(v3 + 88); // bp+548
    int32_t v7 = v2 + 16; // R2
    int32_t v8 = v2 + 28; // R3
    *(int32_t *)(a2 + 124) = v6;
    *(int32_t *)(v2 + 8) = v6;
    *(int32_t *)(v2 + 16) = v7;
    *(int32_t *)(v2 + 20) = v7;
    *(int32_t *)(v2 + 28) = v8;
    *(int32_t *)(v2 + 32) = v8;
    *(int32_t *)(v2 + 12) = v4;
    *(int32_t *)(v2 + 24) = v4;
    int32_t v9 = v3 + 96; // bp+584
    int32_t v10 = *(int32_t *)v9; // bp+584
    *(int32_t *)(v10 + 4) = v2;
    *(int32_t *)v2 = v10;
    *(int32_t *)(v2 + 4) = v9;
    *(int32_t *)(v3 + 96) = v2;
    int32_t * v11 = (int32_t *)(v3 + 92);
    int32_t v12 = *v11 + 1;
    *v11 = v12;
    int32_t v13;
    kteec_add_service(v2, *(int32_t *)1672, v10, v12, v13, 0, 0);
    kteec_add_service(g9, *(int32_t *)1676, v10, v12, v13, 0, 0);
    kteec_add_service(g9, *(int32_t *)1680, v10, v12, v13, 0, 0);
    kteec_add_service(g9, *(int32_t *)1684, v10, v12, v13, 0, 0);
    v8 = g9 + 68;
    int32_t v14 = g9 + 52;
    *(int32_t *)v14 = v14;
    *(int32_t *)(g9 + 56) = v14;
    *(int32_t *)(g9 + 68) = v8;
    *(int32_t *)(g9 + 72) = v8;
    *(int32_t *)(g9 + 40) = g11;
    *(int32_t *)(g9 + 44) = g11;
    *(int32_t *)(g9 + 48) = g11;
    *(int32_t *)(g9 + 60) = g11;
    *(int32_t *)(g9 + 64) = g11;
    *(int32_t *)(g9 + 36) = *(int32_t *)1700;
    if (*(int32_t *)(g9 + 36) == g11) {
        // 0x660
        return -1;
    }
    while (true) {
        // 0x658
        // branch -> 0x658
    }
}

// Address range: 0x6a8 - 0x773
int32_t kteec_service_task(int32_t a1, int32_t a2) {
    int32_t v1 = 81; // bp-44
    kthread_should_stop(0, a1 + 40, (int32_t)&v1, 81, g1);
    // branch -> 0x708
    while (true) {
        // 0x708
        // branch -> 0x708
    }
}

// Address range: 0x774 - 0x7cf
int32_t kteec_mmap(int32_t a1) {
    // 0x774
    return g3 == 0 ? 0 : -11;
}

// Address range: 0x7d0 - 0xddf
int32_t kteec_invoke_command(int32_t a1, uint32_t a2) {
    // 0x7d0
    if (a2 <= 0xffffff8f) {
        // after_if_808_0.thread
        // branch -> 0x814
        // 0x814
        // branch -> 0x94c
        // 0x94c
        return -14;
    }
    // after_if_808_0
    int32_t v1;
    if (v1 != 0) {
        // 0x93c
        // branch -> 0x94c
        // 0x94c
        return -14;
    }
    // 0x814
    // branch -> 0x94c
    // 0x94c
    return -14;
}

// Address range: 0xde0 - 0x16d7
int32_t kteec_ioctl(int32_t a1, int32_t a2, uint32_t a3, int32_t a4) {
    int32_t v1 = g11;
    int32_t v2 = 3564; // bp-4
    g5 = &v2;
    g9 = a1;
    g11 = a3;
    int32_t v3;
    int32_t v4;
    switch (a2) {
        default: {
            // 0xe58
            // branch -> 0xe4c
            // 0xe4c
            g11 = v1;
            return 0;
        }
        case -0x3ffb1200: {
            // 0xe60
            if (a3 > 0xffffffd7) {
                // after_if_e88_0
                if (v3 != 0) {
                    // 0x1360
                    // branch -> 0x1374
                    while (true) {
                        // 0x1374
                        // branch -> 0x1374
                    }
                }
            }
            // 0xe98
            g11 = -14;
            mutex_unlock();
            return &v4;
        }
        case -0x3ffb11ff: {
            // 0xf04
            if (a3 > 0xffffffd7) {
                // after_if_f2c_0
                if (v3 != 0) {
                    // 0x1320
                    // branch -> 0xf98
                    // 0xf98
                    // branch -> 0xe4c
                    // 0xe4c
                    g11 = v1;
                    return -14;
                }
            }
            // 0xf38
            // branch -> 0xf98
            // 0xf98
            // branch -> 0xe4c
            // 0xe4c
            g11 = v1;
            return -14;
        }
        case -0x3ffb11fe: {
            // 0xfa8
            if (a3 > 0xffffffe7) {
                // after_if_fcc_0
                if (v3 != 0) {
                    // 0x1344
                    // branch -> 0xe4c
                    // 0xe4c
                    g11 = v1;
                    return -14;
                }
            }
            // 0xfdc
            g11 = -14;
            mutex_unlock();
            return &v4;
        }
        case -0x3ffb11fd: {
            // 0x11fc
            if (a3 <= 0xffffffe7) {
                // after_if_1224_0.thread
                // branch -> 0x1230
                // 0x1230
                g11 = -14;
                mutex_unlock();
                return &v4;
            }
            int32_t result = &v4; // 0x1230_0
            if (v3 == 0) {
                // 0x1230
                g11 = -14;
                mutex_unlock();
                return result;
            }
            // 0x1330
            g11 = -14;
            mutex_unlock();
            return result;
        }
        case -0x3ffb11fc: {
            // 0xe2c
            kteec_invoke_command(*(int32_t *)(a1 + 124), a3);
            // branch -> 0xe4c
            // 0xe4c
            g11 = v1;
            return -14;
        }
    }
}

// Address range: 0x16d8 - 0x190f
int32_t kteec_init(int32_t a1) {
    int32_t v1 = 0x16e4; // bp-4
    g5 = &v1;
    int32_t v2 = *(int32_t *)0x18f8; // 0x16f0
    g9 = v2;
    if (*(int32_t *)(v2 + 20) == 1) {
        // if_16fc_0_true
        return 0;
    }
    // 0x1704
    g11 = 2;
    *(int32_t *)(v2 + 104) = (int32_t)kteec_do_secure_call;
    *(int32_t *)(g9 + 112) = (int32_t)kteec_do_secure_call;
    *(int32_t *)(g9 + 24) = 0xc800000;
    g10 = 0xc800000;
    int32_t v3 = *(int32_t *)(g9 + 116); // 0x175c
    if (v3 != 0) {
        // 0x1768
        kteec_wsm_free(v3);
        // branch -> 0x176c
    }
    int32_t v4 = *(int32_t *)(g9 + 120); // 0x176c
    if (v4 != 0) {
        // 0x1778
        kteec_wsm_free(v4);
        // branch -> 0x177c
    }
    int32_t v5 = *(int32_t *)(g9 + 124); // 0x177c
    if (v5 != 0) {
        // 0x1788
        kteec_wsm_free(v5);
        // branch -> 0x178c
    }
    int32_t v6 = *(int32_t *)(g9 + 128); // 0x178c
    if (v6 != 0) {
        // 0x1798
        kteec_wsm_free(v6);
        // branch -> 0x17a0
    }
    while (true) {
        // 0x17a0
        // branch -> 0x17a0
    }
}

// Address range: 0x1910 - 0x19cb
int32_t kteec_exit(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5) {
    int32_t v1 = 0x191c; // bp-4
    g5 = &v1;
    int32_t v2 = *(int32_t *)0x19c4; // 0x1924
    g9 = v2;
    int32_t v3 = *(int32_t *)(v2 + 116); // 0x1928
    if (v3 != 0) {
        // 0x1934
        kteec_wsm_free(v3);
        *(int32_t *)(g9 + 116) = 0;
        v2 = g9;
        // branch -> 0x1940
    }
    int32_t v4 = *(int32_t *)(v2 + 120); // 0x1940
    g10 = *(int32_t *)0x19c4;
    if (v4 != 0) {
        // 0x1950
        kteec_wsm_free(v4);
        *(int32_t *)(g10 + 120) = 0;
        v2 = g9;
        // branch -> 0x195c
    }
    int32_t v5 = *(int32_t *)(v2 + 124); // 0x195c
    g10 = *(int32_t *)0x19c4;
    if (v5 != 0) {
        // 0x196c
        kteec_wsm_free(v5);
        *(int32_t *)(g10 + 124) = 0;
        v2 = g9;
        // branch -> 0x1978
    }
    int32_t v6 = *(int32_t *)(v2 + 128); // 0x1978
    g10 = *(int32_t *)0x19c4;
    if (v6 != 0) {
        // 0x1988
        kteec_wsm_free(v6);
        *(int32_t *)(g10 + 128) = 0;
        v2 = g9;
        // branch -> 0x1994
    }
    // 0x1994
    if (*(int32_t *)(v2 + 108) == 0) {
        while (true) {
            // 0x19a8
            // branch -> 0x19a8
        }
    } else {
        while (true) {
            // 0x19a0
            // branch -> 0x19a0
        }
    }
}

// Address range: 0x19cc - 0x19f7
int32_t size_of_block(int32_t a1, int32_t a2, int32_t a3) {
    // 0x19cc
    abort();
    // UNREACHABLE
}

// Address range: 0x19f8 - 0x1a2b
int32_t next_free_block(int32_t a1, int32_t a2, int32_t a3) {
    // 0x19f8
    abort();
    // UNREACHABLE
}

// Address range: 0x1a2c - 0x1a63
int32_t link_2_next_free_block(int32_t a1, int32_t a2, int32_t a3, int32_t a4) {
    // 0x1a2c
    abort();
    // UNREACHABLE
}

// Address range: 0x1a64 - 0x1acf
int32_t kteec_wsm_init(int32_t * a1, uint32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13, int32_t a14, int32_t a15) {
    int32_t v1 = (int32_t)a1;
    g2 = v1;
    int32_t v2 = g9; // 0x1a68
    int32_t v3 = g10; // 0x1a68
    int32_t v4 = g11; // 0x1a68
    int32_t v5 = g12; // 0x1a68
    int32_t v6 = g13; // 0x1a68
    int32_t v7 = g14; // 0x1a68
    int32_t v8 = g4; // 0x1a68
    int32_t v9 = g6; // 0x1a68
    int32_t v10 = g1; // 0x1a68
    g1 = 0x1a78;
    int32_t v11 = a2 / 8; // 0x1a78
    int32_t v12;
    g6 = &v12;
    g7 = v11;
    int32_t result = 8 * v11 + v1; // 0x1a90
    g3 = result;
    int32_t v13; // bp+12
    int32_t v14 = &v13; // 0x1a94_0
    v12 = v1;
    v13 = v14;
    *a1 = v11 - 1;
    *(int32_t *)(v1 + 4) = (int32_t)(a2 < 8);
    *(int32_t *)(result - 8) = g7;
    *(int32_t *)(result - 4) = 0;
    g8 = v10;
    g9 = a4;
    g10 = v2;
    g11 = v3;
    g12 = v4;
    g13 = v5;
    g14 = v6;
    g4 = v7;
    g5 = v8;
    ((int32_t (*)(int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t))v9)(v10, g7, result, v1, v9, v10, 0x1a70, v12, (int32_t)kteec_do_secure_call, 1, v13, v14, a10, v11, (int32_t)kteec_do_secure_call, (int32_t)kteec_do_secure_call, (int32_t)kteec_do_secure_call, a15);
    return result;
}

// Address range: 0x1ad0 - 0x1d2b
int32_t kteec_wsm_alloc(uint32_t a1) {
    // 0x1ad0
    if (a1 != 0) {
        int32_t v1 = a1 / 8; // 0x1b00
        int32_t v2 = 0; // R9
        int32_t v3 = v1; // R8
        uint32_t v4 = v1; // 0x1cfc
        if (a1 % 8 != 0) {
            int32_t v5 = v1 + 1; // 0x1ba4
            v3 = v5;
            v2 = 0;
            v4 = v5;
            // branch -> 0x1b10
        }
        int32_t v6 = *(int32_t *)0x1d28; // 0x1b10
        int32_t v7 = *(int32_t *)(v6 + 24); // 0x1b20
        int32_t v8 = *(int32_t *)(v6 + 28); // 0x1b20
        int32_t v9 = *(int32_t *)v6; // 0x1b24
        int32_t * v10 = (int32_t *)(v6 + 32); // 0x1b28_0
        int32_t v11 = *v10; // 0x1b28
        int32_t * v12 = (int32_t *)(v6 + 36); // 0x1b28_1
        int32_t v13 = *v12; // 0x1b28
        int32_t v14 = v11; // R6
        if (v11 != v7 || v13 != v8) {
            int32_t v15 = 8 * v11; // 0x1b3891
            int32_t v16 = 1; // 0x1bb8388
            while (true) {
                int32_t v17 = v15 + v9; // 0x1b4c
                uint32_t v18 = *(int32_t *)v17; // 0x1b4c
                int32_t result = v18; // R0
                int32_t v19 = *(int32_t *)(v17 + 4); // 0x1b4c
                bool v20;
                int32_t v21;
                int32_t v22; // 0x1c4c
                int32_t v23; // 0x1c58
                int32_t v24; // 0x1c94
                int32_t v25; // 0x1c60
                int32_t v26; // 0x1c9852
                int32_t v27; // 0x1c3c
                int32_t v28; // 0x1c40
                int32_t v29; // 0x1c68
                int32_t v30; // 0x1c9c
                int32_t v31; // 0x1c9c54
                int32_t v32; // 0x1ccc
                int32_t v33; // 0x1cd0
                int32_t v34; // 0x1c38
                int32_t v35; // 0x1c44
                int32_t v36; // 0x1c5447
                int32_t v37; // 0x1c8c
                int32_t v38; // 0x1cb4
                int32_t v39; // 0x1cc8
                int32_t v40; // 0x1cd4
                int32_t v41; // 0x1c34
                int32_t v42; // 0x1cb4
                uint32_t v43; // 0x1c3c
                uint32_t v44; // 0x1ccc
                int32_t v45; // 0x1b4c119
                uint32_t v46; // 0x1bec
                int32_t v47; // 0x1bfc
                uint32_t v48; // 0x1c1c
                int32_t v49; // 0x1c5c
                int32_t v50; // 0x1c00
                if (v19 == 0) {
                    // if_1b58_0_true
                    if (v18 >= v4) {
                        // after_if_1bb4_0
                        if (v18 == v4) {
                            // 0x1cdc
                            if (v16 != (int32_t)kteec_do_secure_call) {
                                int32_t v51 = 8 * (v11 + v4) + v9; // 0x1cec
                                *v10 = *(int32_t *)v51;
                                *v12 = *(int32_t *)(v51 + 4);
                                up();
                                return result;
                            }
                            int32_t v52 = 8 * (v11 + v4) + v9; // 0x1d10
                            int32_t result2 = 8 * (*(int32_t *)(8 * v11 + v9) + v11); // 0x1d18
                            int32_t v53 = result2 + v9; // 0x1d1c
                            *(int32_t *)v53 = *(int32_t *)v52;
                            *(int32_t *)(v53 + 4) = *(int32_t *)(v52 + 4);
                            up();
                            return result2;
                        }
                        v45 = 0;
                        // 0x1bc0
                        v47 = v18 - v4;
                        v50 = v18 < v4;
                        v20 = v47 == 1 & v45 == v50;
                        if (v16 != (int32_t)kteec_do_secure_call) {
                            // 0x1bd0
                            if (v20) {
                                // 0x1c84
                                v37 = 8 * (v18 + v11) + v9;
                                *v10 = *(int32_t *)v37;
                                *v12 = *(int32_t *)(v37 + 4);
                                v30 = v17;
                                v24 = v3;
                                // branch -> 0x1c94
                                // 0x1c94
                                *(int32_t *)v30 = v24 + 1;
                                *(int32_t *)(v30 + 4) = (int32_t)(v24 == -1) + v2;
                                up();
                                return result;
                            }
                            // 0x1be4
                            v46 = v11 + v4 + 1;
                            *v10 = v46;
                            *v12 = (int32_t)(v46 < v11) + v13;
                            v23 = v47;
                            // branch -> 0x1c54
                            // 0x1c54
                            v49 = 8 * (v14 + v3) + v9;
                            *(int32_t *)(v49 + 8) = v23 - 1;
                            *(int32_t *)(v49 + 12) = v45 - v50 - (int32_t)(v23 == 0);
                            v29 = v17;
                            *(int32_t *)v29 = v3;
                            *(int32_t *)(v29 + 4) = v2;
                            return *(int32_t *)v6 + 8 + 8 * v14;
                        }
                        // 0x1bfc
                        if (v20) {
                            // 0x1ca4
                            v38 = 8 * (v18 + v11) + v9;
                            v42 = *(int32_t *)v38;
                            result = v42;
                            v39 = 8 * (*(int32_t *)(8 * v11 + v9) + v11) + v9;
                            *(int32_t *)v39 = v42;
                            *(int32_t *)(v39 + 4) = *(int32_t *)(v38 + 4);
                            v32 = v17;
                            v44 = *(int32_t *)v32;
                            v33 = v3;
                            v40 = v2;
                            v31 = v32;
                            v26 = v40;
                            v36 = v33;
                            v22 = v44 - v33;
                            v21 = *(int32_t *)(v32 + 4) - v40 + (int32_t)(v44 < v33);
                            // branch -> 0x1c48
                        } else {
                            // 0x1c10
                            v48 = v11 + v4 + 1;
                            v41 = 8 * (*(int32_t *)(8 * v11 + v9) + v11);
                            result = v41;
                            v34 = v41 + v9;
                            *(int32_t *)v34 = v48;
                            *(int32_t *)(v34 + 4) = (int32_t)(v48 < v11) + v13;
                            v27 = v17;
                            v43 = *(int32_t *)v27;
                            v28 = v3;
                            v35 = v2;
                            v31 = v27;
                            v26 = v35;
                            v36 = v28;
                            v22 = v43 - v28;
                            v21 = *(int32_t *)(v27 + 4) - v35 + (int32_t)(v43 < v28);
                            // branch -> 0x1c48
                        }
                        // 0x1c48
                        if (v21 == 0) {
                            // after_if_1c4c_0
                            if (v22 == 1) {
                                v30 = v31;
                                v24 = v36;
                                // 0x1c94
                                *(int32_t *)v30 = v24 + 1;
                                *(int32_t *)(v30 + 4) = (int32_t)(v24 == -1) + v26;
                                up();
                                return result;
                            }
                            v25 = 0;
                            v23 = v22;
                        } else {
                            v25 = v21;
                            v23 = v22;
                        }
                        // 0x1c54
                        v49 = 8 * (v14 + v36) + v9;
                        *(int32_t *)(v49 + 8) = v23 - 1;
                        *(int32_t *)(v49 + 12) = v25 - (int32_t)(v23 == 0);
                        v29 = v17;
                        *(int32_t *)v29 = v3;
                        *(int32_t *)(v29 + 4) = v2;
                        return *(int32_t *)v6 + 8 + 8 * v14;
                    }
                    int32_t v54 = 8 * (v18 + v11) + v9; // 0x1b68
                    int32_t v55 = *(int32_t *)v54; // 0x1b68
                    int32_t v56 = *(int32_t *)(v54 + 4); // 0x1b68
                    if (v56 == v8) {
                        // after_if_1b7c_0
                        if (v55 == v7) {
                            // 0x1b90
                            // branch -> 0x1b94
                            while (true) {
                                // 0x1b94
                                // branch -> 0x1b94
                            }
                        }
                    } else {
                        // after_if_1b7c_0.thread
                        v8 = v56;
                        // branch -> 0x1b34
                    }
                    // 0x1b34
                    v14 = v55;
                    v15 = 8 * v55;
                    v11 = v55;
                    v13 = v8;
                    v16 = kteec_do_secure_call;
                    // branch -> 0x1b4c
                    continue;
                } else {
                    // after_if_1bb4_0.thread
                    v45 = v19;
                    // branch -> 0x1bc0
                }
                // 0x1bc0
                v47 = v18 - v4;
                v50 = v18 < v4;
                v20 = v47 == 1 & v45 == v50;
                if (v16 != (int32_t)kteec_do_secure_call) {
                    // 0x1bd0
                    if (v20) {
                        // 0x1c84
                        v37 = 8 * (v18 + v11) + v9;
                        *v10 = *(int32_t *)v37;
                        *v12 = *(int32_t *)(v37 + 4);
                        v30 = v17;
                        v24 = v3;
                        // branch -> 0x1c94
                        // 0x1c94
                        *(int32_t *)v30 = v24 + 1;
                        *(int32_t *)(v30 + 4) = (int32_t)(v24 == -1) + v2;
                        up();
                        return result;
                    }
                    // 0x1be4
                    v46 = v11 + v4 + 1;
                    *v10 = v46;
                    *v12 = (int32_t)(v46 < v11) + v13;
                    v23 = v47;
                    // branch -> 0x1c54
                    // 0x1c54
                    v49 = 8 * (v14 + v3) + v9;
                    *(int32_t *)(v49 + 8) = v23 - 1;
                    *(int32_t *)(v49 + 12) = v45 - v50 - (int32_t)(v23 == 0);
                    v29 = v17;
                    *(int32_t *)v29 = v3;
                    *(int32_t *)(v29 + 4) = v2;
                    return *(int32_t *)v6 + 8 + 8 * v14;
                }
                // 0x1bfc
                if (v20) {
                    // 0x1ca4
                    v38 = 8 * (v18 + v11) + v9;
                    v42 = *(int32_t *)v38;
                    result = v42;
                    v39 = 8 * (*(int32_t *)(8 * v11 + v9) + v11) + v9;
                    *(int32_t *)v39 = v42;
                    *(int32_t *)(v39 + 4) = *(int32_t *)(v38 + 4);
                    v32 = v17;
                    v44 = *(int32_t *)v32;
                    v33 = v3;
                    v40 = v2;
                    v31 = v32;
                    v26 = v40;
                    v36 = v33;
                    v22 = v44 - v33;
                    v21 = *(int32_t *)(v32 + 4) - v40 + (int32_t)(v44 < v33);
                    // branch -> 0x1c48
                } else {
                    // 0x1c10
                    v48 = v11 + v4 + 1;
                    v41 = 8 * (*(int32_t *)(8 * v11 + v9) + v11);
                    result = v41;
                    v34 = v41 + v9;
                    *(int32_t *)v34 = v48;
                    *(int32_t *)(v34 + 4) = (int32_t)(v48 < v11) + v13;
                    v27 = v17;
                    v43 = *(int32_t *)v27;
                    v28 = v3;
                    v35 = v2;
                    v31 = v27;
                    v26 = v35;
                    v36 = v28;
                    v22 = v43 - v28;
                    v21 = *(int32_t *)(v27 + 4) - v35 + (int32_t)(v43 < v28);
                    // branch -> 0x1c48
                }
                // 0x1c48
                if (v21 == 0) {
                    // after_if_1c4c_0
                    if (v22 == 1) {
                        v30 = v31;
                        v24 = v36;
                        // 0x1c94
                        *(int32_t *)v30 = v24 + 1;
                        *(int32_t *)(v30 + 4) = (int32_t)(v24 == -1) + v26;
                        up();
                        return result;
                    }
                    v25 = 0;
                    v23 = v22;
                } else {
                    v25 = v21;
                    v23 = v22;
                }
                // 0x1c54
                v49 = 8 * (v14 + v36) + v9;
                *(int32_t *)(v49 + 8) = v23 - 1;
                *(int32_t *)(v49 + 12) = v25 - (int32_t)(v23 == 0);
                v29 = v17;
                *(int32_t *)v29 = v3;
                *(int32_t *)(v29 + 4) = v2;
                return *(int32_t *)v6 + 8 + 8 * v14;
            }
        }
        while (true) {
            // 0x1b94
            // branch -> 0x1b94
        }
    }
    while (true) {
        // 0x1b94
        // branch -> 0x1b94
    }
}

// Address range: 0x1d2c - 0x1f07
int32_t kteec_wsm_free(int32_t a1) {
    int32_t v1 = g9; // 0x1d30
    int32_t v2 = g10; // 0x1d30
    int32_t v3 = g11; // 0x1d30
    int32_t v4 = g12; // 0x1d30
    int32_t v5 = g13; // 0x1d30
    int32_t v6 = g14; // 0x1d30
    int32_t v7 = g4; // 0x1d30
    int32_t v8 = g5; // 0x1d30
    int32_t v9 = 0x1d38; // bp-4
    g5 = &v9;
    int32_t v10 = *(int32_t *)0x1f00; // 0x1d44
    g11 = v10;
    int32_t v11 = *(int32_t *)v10; // 0x1d54
    int32_t v12 = *(int32_t *)(v10 + 32); // 0x1d58
    int32_t v13 = *(int32_t *)(v10 + 36); // 0x1d58
    int32_t v14 = a1 - 8 - v11; // 0x1d60
    int32_t v15 = v14 / 8; // 0x1d64
    g12 = v15;
    uint32_t v16 = v14 >> 31; // 0x1d68
    g14 = v16;
    g13 = v15;
    int32_t * v17; // 0x1e28_0
    int32_t * v18; // 0x1e28_1
    int32_t v19; // LR
    int32_t result; // R0
    int32_t v20; // R1
    int32_t v21; // R5
    int32_t v22;
    int32_t v23; // 0x1e00
    int32_t v24; // 0x1e10
    int32_t v25; // 0x1eb0
    int32_t v26; // 0x1ee4
    int32_t result2; // 0x1e38
    uint32_t v27; // 0x1e78
    uint32_t v28; // 0x1e9c
    int32_t v29; // 0x1ebc
    int32_t v30; // 0x1ee4
    uint32_t v31; // 0x1ec0
    int32_t v32; // 0x1ee8
    int32_t v33; // 0x1e54
    int32_t v34; // 0x1eac
    int32_t v35; // 0x1ec8
    int32_t v36; // 0x1ed0
    int32_t v37; // 0x1ef8
    int32_t v38; // 0x1d94
    int32_t v39; // 0x1db0
    int32_t v40; // 0x1dc0
    int32_t v41; // 0x1dfc
    int32_t v42; // 0x1e0c
    int32_t v43; // 0x1e10
    int32_t v44; // 0x1e28
    int32_t v45; // 0x1e50
    int32_t v46; // 0x1e74
    int32_t v47; // 0x1e98
    int32_t v48; // 0x1eb0
    int32_t v49; // 0x1eec
    int32_t v50; // 0x1d88
    int32_t v51; // 0x1db0
    int32_t v52; // 0x1dc0
    int32_t v53; // 0x1e10
    uint32_t v54; // 0x1e28
    int32_t v55; // 0x1e4c
    int32_t v56; // 0x1e74
    int32_t v57; // 0x1e90
    int32_t result3; // 0x1ee0
    uint32_t v58; // 0x1eec
    int32_t v59; // 0x1db8
    uint32_t v60; // 0x1dd8
    int32_t v61; // 0x1ddc10
    uint32_t v62; // 0x1e5c
    int32_t v63; // 0x1e941
    uint32_t v64; // 0x1eb4
    int32_t v65; // 0x1db0
    int32_t v66; // 0x1dc0
    uint32_t v67; // 0x1dd8
    int32_t v68; // 0x1e28
    uint32_t v69; // 0x1e2c
    int32_t v70; // 0x1e74
    uint32_t v71; // 0x1e80
    int32_t v72; // 0x1e98
    int32_t v73; // 0x1ea4
    int32_t v74; // 0x1eb4
    int32_t v75; // 0x1eec
    uint32_t v76; // 0x1ef0
    uint32_t v77; // 0x1e5c
    uint32_t v78; // 0x1ed0
    int32_t v79; // 0x1e34
    int32_t v80; // 0x1eb8
    if (v16 != v13) {
        // after_if_1d74_0
        if (v16 < v13) {
            // 0x1e24
            v44 = 8 * v15 + v11;
            v17 = (int32_t *)v44;
            v54 = *v17;
            v18 = (int32_t *)(v44 + 4);
            v68 = *v18;
            v69 = v54 + v15;
            v79 = v68 + v16 + (int32_t)(v69 < v54);
            g10 = v79;
            result2 = v69 + 1;
            if (v12 == result2 && v13 == v79 + (int32_t)(v69 == -1)) {
                // 0x1e5c
                v62 = *(int32_t *)(v10 + 24);
                result = v62;
                v77 = *(int32_t *)(v10 + 28);
                if (v13 == v77) {
                    // if_1e64_0_true
                    if (v12 >= v62) {
                        // 0x1e4c
                        v55 = 8 * v69;
                        g9 = v55;
                        v45 = v55 + v11;
                        *(int32_t *)v45 = v12;
                        *(int32_t *)(v45 + 4) = v13;
                        // branch -> 0x1e54
                        // 0x1e54
                        v33 = g11;
                        *(int32_t *)(v33 + 32) = g13;
                        *(int32_t *)(v33 + 36) = g14;
                        up();
                        return result;
                    }
                } else {
                    // after_if_1e64_0
                    if (v13 >= v77) {
                        // 0x1e4c
                        v55 = 8 * v69;
                        g9 = v55;
                        v45 = v55 + v11;
                        *(int32_t *)v45 = v12;
                        *(int32_t *)(v45 + 4) = v13;
                        // branch -> 0x1e54
                        // 0x1e54
                        v33 = g11;
                        *(int32_t *)(v33 + 32) = g13;
                        *(int32_t *)(v33 + 36) = g14;
                        up();
                        return result;
                    }
                }
                // 0x1e6c
                g9 = v54;
                g10 = v68;
                v46 = 8 * v12 + v11;
                v56 = *(int32_t *)v46;
                v70 = *(int32_t *)(v46 + 4);
                v27 = v56 + 1;
                v71 = v27 + v54;
                *v17 = v71;
                *v18 = v70 + v68 + (int32_t)(v56 == -1) + (int32_t)(v71 < v27);
                // branch -> 0x1e54
                // 0x1e54
                v33 = g11;
                *(int32_t *)(v33 + 32) = g13;
                *(int32_t *)(v33 + 36) = g14;
                up();
                return result;
            }
            // 0x1e4c
            v55 = 8 * v69;
            g9 = v55;
            v45 = v55 + v11;
            *(int32_t *)v45 = v12;
            *(int32_t *)(v45 + 4) = v13;
            // branch -> 0x1e54
            // 0x1e54
            v33 = g11;
            *(int32_t *)(v33 + 32) = g13;
            *(int32_t *)(v33 + 36) = g14;
            up();
            return result2;
        }
        // after_if_1d80_0
        if (v13 < v16) {
            v61 = v13;
            v59 = v12;
            while (true) {
                // 0x1dac
                v39 = 8 * v59 + v11;
                v51 = *(int32_t *)v39;
                v65 = *(int32_t *)(v39 + 4);
                v19 = v39;
                v40 = 8 * (v51 + v59) + v11;
                v52 = *(int32_t *)v40;
                result = v52;
                v66 = *(int32_t *)(v40 + 4);
                v20 = v66;
                if (v66 == v16) {
                    goto lab_if_1dc8_0_true;
                }
                goto lab_after_if_1dc8_0;
            }
        } else {
            // 0x1d88
            v50 = 8 * v12;
            g4 = v50;
            result = v12;
            v20 = v13;
            v38 = v50 + v11;
            v34 = v38;
            v60 = v12;
            v63 = *(int32_t *)v38;
            v22 = *(int32_t *)(v38 + 4);
            // branch -> 0x1dd4
        }
        // 0x1dd4
        v67 = v63 + v60;
        if (v67 + 1 == v15 && v22 + v13 + (int32_t)(v67 < v60) + (int32_t)(v67 == -1) == v16) {
            // 0x1e90
            v57 = 8 * v15;
            g12 = v57;
            v47 = v57 + v11;
            v72 = *(int32_t *)(v47 + 4);
            v28 = v63 + 1;
            v73 = *(int32_t *)v47 + v28;
            v21 = (int32_t)(v63 == -1) + v22 + v72 + (int32_t)(v73 < v28);
            *(int32_t *)v34 = v73;
            *(int32_t *)(v34 + 4) = v21;
            v25 = v11;
            v48 = g12 + v25;
            v64 = g13;
            v74 = v64 + *(int32_t *)v48;
            g13 = v74;
            v80 = g14 + *(int32_t *)(v48 + 4) + (int32_t)(v74 < v64);
            g14 = v80;
            v29 = v74 + 1;
            v31 = v80 + (int32_t)(v74 == -1);
            v35 = result;
            if (v29 == v35 && v31 == v20) {
                // 0x1ed0
                v36 = g11;
                v78 = *(int32_t *)(v36 + 28);
                if (v31 == v78) {
                    // if_1ed8_0_true
                    if (v29 >= *(int32_t *)(v36 + 24)) {
                        // 0x1e0c
                        v43 = 8 * v74 + v25;
                        *(int32_t *)v43 = v29;
                        *(int32_t *)(v43 + 4) = v20;
                        g9 = v1;
                        g10 = v2;
                        g11 = v3;
                        g12 = v4;
                        g13 = v5;
                        g14 = v6;
                        g4 = v7;
                        g5 = v8;
                        return *(int32_t *)0x1f04;
                    }
                } else {
                    // after_if_1ed8_0
                    if (v31 >= v78) {
                        // 0x1e0c
                        v43 = 8 * v74 + v25;
                        *(int32_t *)v43 = v29;
                        *(int32_t *)(v43 + 4) = v20;
                        g9 = v1;
                        g10 = v2;
                        g11 = v3;
                        g12 = v4;
                        g13 = v5;
                        g14 = v6;
                        g4 = v7;
                        g5 = v8;
                        return *(int32_t *)0x1f04;
                    }
                }
                // 0x1ee0
                result3 = 8 * v29;
                v26 = v73;
                v30 = v26 + 1;
                g9 = v30;
                v32 = (int32_t)(v26 == -1) + v21;
                g10 = v32;
                v49 = result3 + v25;
                v58 = *(int32_t *)v49;
                v75 = *(int32_t *)(v49 + 4);
                v76 = v58 + v30;
                v37 = v38;
                *(int32_t *)v37 = v76;
                *(int32_t *)(v37 + 4) = v75 + v32 + (int32_t)(v76 < v58);
                up();
                return result3;
            }
            v53 = v35;
            v24 = v25;
            v42 = v74;
        } else {
            // 0x1df4
            v41 = 8 * v67 + v11;
            *(int32_t *)v41 = v15;
            *(int32_t *)(v41 + 4) = g14;
            v23 = v11;
            v53 = result;
            v24 = v23;
            v42 = g13 + *(int32_t *)(v23 + 8 * v15);
            // branch -> 0x1e0c
        }
        // 0x1e0c
        v43 = 8 * v42 + v24;
        *(int32_t *)v43 = v53;
        *(int32_t *)(v43 + 4) = v20;
        g9 = v1;
        g10 = v2;
        g11 = v3;
        g12 = v4;
        g13 = v5;
        g14 = v6;
        g4 = v7;
        g5 = v8;
        return *(int32_t *)0x1f04;
    }
    // if_1d74_0_true
    if (v15 < v12) {
        // 0x1e24
        v44 = 8 * v15 + v11;
        v17 = (int32_t *)v44;
        v54 = *v17;
        v18 = (int32_t *)(v44 + 4);
        v68 = *v18;
        v69 = v54 + v15;
        v79 = v68 + v16 + (int32_t)(v69 < v54);
        g10 = v79;
        result2 = v69 + 1;
        if (v12 == result2 && v13 == v79 + (int32_t)(v69 == -1)) {
            // 0x1e5c
            v62 = *(int32_t *)(v10 + 24);
            result = v62;
            v77 = *(int32_t *)(v10 + 28);
            if (v13 == v77) {
                // if_1e64_0_true
                if (v12 >= v62) {
                    // 0x1e4c
                    v55 = 8 * v69;
                    g9 = v55;
                    v45 = v55 + v11;
                    *(int32_t *)v45 = v12;
                    *(int32_t *)(v45 + 4) = v13;
                    // branch -> 0x1e54
                    // 0x1e54
                    v33 = g11;
                    *(int32_t *)(v33 + 32) = g13;
                    *(int32_t *)(v33 + 36) = g14;
                    up();
                    return result;
                }
            } else {
                // after_if_1e64_0
                if (v13 >= v77) {
                    // 0x1e4c
                    v55 = 8 * v69;
                    g9 = v55;
                    v45 = v55 + v11;
                    *(int32_t *)v45 = v12;
                    *(int32_t *)(v45 + 4) = v13;
                    // branch -> 0x1e54
                    // 0x1e54
                    v33 = g11;
                    *(int32_t *)(v33 + 32) = g13;
                    *(int32_t *)(v33 + 36) = g14;
                    up();
                    return result;
                }
            }
            // 0x1e6c
            g9 = v54;
            g10 = v68;
            v46 = 8 * v12 + v11;
            v56 = *(int32_t *)v46;
            v70 = *(int32_t *)(v46 + 4);
            v27 = v56 + 1;
            v71 = v27 + v54;
            *v17 = v71;
            *v18 = v70 + v68 + (int32_t)(v56 == -1) + (int32_t)(v71 < v27);
            // branch -> 0x1e54
            // 0x1e54
            v33 = g11;
            *(int32_t *)(v33 + 32) = g13;
            *(int32_t *)(v33 + 36) = g14;
            up();
            return result;
        }
        // 0x1e4c
        v55 = 8 * v69;
        g9 = v55;
        v45 = v55 + v11;
        *(int32_t *)v45 = v12;
        *(int32_t *)(v45 + 4) = v13;
        // branch -> 0x1e54
        // 0x1e54
        v33 = g11;
        *(int32_t *)(v33 + 32) = g13;
        *(int32_t *)(v33 + 36) = g14;
        up();
        return result2;
    }
    // if_1d80_0_true
    if (v12 < v15) {
        v61 = v13;
        v59 = v12;
        while (true) {
            // 0x1dac
            v39 = 8 * v59 + v11;
            v51 = *(int32_t *)v39;
            v65 = *(int32_t *)(v39 + 4);
            v19 = v39;
            v40 = 8 * (v51 + v59) + v11;
            v52 = *(int32_t *)v40;
            result = v52;
            v66 = *(int32_t *)(v40 + 4);
            v20 = v66;
            if (v66 == v16) {
              lab_if_1dc8_0_true:
                // if_1dc8_0_true
                if (v52 >= v15) {
                    v34 = v39;
                    v60 = v59;
                    v63 = v51;
                    v22 = v65;
                    // 0x1dd4
                    v67 = v63 + v60;
                    if (v67 + 1 != v15 || v22 + v61 + (int32_t)(v67 < v60) + (int32_t)(v67 == -1) != v16) {
                        // 0x1df4
                        v41 = 8 * v67 + v11;
                        *(int32_t *)v41 = v15;
                        *(int32_t *)(v41 + 4) = g14;
                        v23 = v11;
                        // branch -> 0x1e0c
                        // 0x1e0c
                        v43 = 8 * (g13 + *(int32_t *)(v23 + 8 * v15)) + v23;
                        *(int32_t *)v43 = result;
                        *(int32_t *)(v43 + 4) = v20;
                        g9 = v1;
                        g10 = v2;
                        g11 = v3;
                        g12 = v4;
                        g13 = v5;
                        g14 = v6;
                        g4 = v7;
                        g5 = v8;
                        return *(int32_t *)0x1f04;
                    }
                    // 0x1e90
                    v57 = 8 * v15;
                    g12 = v57;
                    v47 = v57 + v11;
                    v72 = *(int32_t *)(v47 + 4);
                    v28 = v63 + 1;
                    v73 = *(int32_t *)v47 + v28;
                    v21 = (int32_t)(v63 == -1) + v22 + v72 + (int32_t)(v73 < v28);
                    *(int32_t *)v34 = v73;
                    *(int32_t *)(v34 + 4) = v21;
                    v25 = v11;
                    v48 = g12 + v25;
                    v64 = g13;
                    v74 = v64 + *(int32_t *)v48;
                    g13 = v74;
                    v80 = g14 + *(int32_t *)(v48 + 4) + (int32_t)(v74 < v64);
                    g14 = v80;
                    v29 = v74 + 1;
                    v31 = v80 + (int32_t)(v74 == -1);
                    v35 = result;
                    if (v29 == v35 && v31 == v20) {
                        // 0x1ed0
                        v36 = g11;
                        v78 = *(int32_t *)(v36 + 28);
                        if (v31 == v78) {
                            // if_1ed8_0_true
                            if (v29 >= *(int32_t *)(v36 + 24)) {
                                // 0x1e0c
                                v43 = 8 * v74 + v25;
                                *(int32_t *)v43 = v29;
                                *(int32_t *)(v43 + 4) = v20;
                                g9 = v1;
                                g10 = v2;
                                g11 = v3;
                                g12 = v4;
                                g13 = v5;
                                g14 = v6;
                                g4 = v7;
                                g5 = v8;
                                return *(int32_t *)0x1f04;
                            }
                        } else {
                            // after_if_1ed8_0
                            if (v31 >= v78) {
                                // 0x1e0c
                                v43 = 8 * v74 + v25;
                                *(int32_t *)v43 = v29;
                                *(int32_t *)(v43 + 4) = v20;
                                g9 = v1;
                                g10 = v2;
                                g11 = v3;
                                g12 = v4;
                                g13 = v5;
                                g14 = v6;
                                g4 = v7;
                                g5 = v8;
                                return *(int32_t *)0x1f04;
                            }
                        }
                        // 0x1ee0
                        result3 = 8 * v29;
                        v26 = v73;
                        v30 = v26 + 1;
                        g9 = v30;
                        v32 = (int32_t)(v26 == -1) + v21;
                        g10 = v32;
                        v49 = result3 + v25;
                        v58 = *(int32_t *)v49;
                        v75 = *(int32_t *)(v49 + 4);
                        v76 = v58 + v30;
                        v37 = v19;
                        *(int32_t *)v37 = v76;
                        *(int32_t *)(v37 + 4) = v75 + v32 + (int32_t)(v76 < v58);
                        up();
                        return result3;
                    }
                    // 0x1e0c
                    v43 = 8 * v74 + v25;
                    *(int32_t *)v43 = v35;
                    *(int32_t *)(v43 + 4) = v20;
                    g9 = v1;
                    g10 = v2;
                    g11 = v3;
                    g12 = v4;
                    g13 = v5;
                    g14 = v6;
                    g4 = v7;
                    g5 = v8;
                    return *(int32_t *)0x1f04;
                }
            } else {
              lab_after_if_1dc8_0:
                // after_if_1dc8_0
                if (v66 >= v16) {
                    v34 = v39;
                    v60 = v59;
                    v63 = v51;
                    v22 = v65;
                    // 0x1dd4
                    v67 = v63 + v60;
                    if (v67 + 1 != v15 || v22 + v61 + (int32_t)(v67 < v60) + (int32_t)(v67 == -1) != v16) {
                        // 0x1df4
                        v41 = 8 * v67 + v11;
                        *(int32_t *)v41 = v15;
                        *(int32_t *)(v41 + 4) = g14;
                        v23 = v11;
                        // branch -> 0x1e0c
                        // 0x1e0c
                        v43 = 8 * (g13 + *(int32_t *)(v23 + 8 * v15)) + v23;
                        *(int32_t *)v43 = result;
                        *(int32_t *)(v43 + 4) = v20;
                        g9 = v1;
                        g10 = v2;
                        g11 = v3;
                        g12 = v4;
                        g13 = v5;
                        g14 = v6;
                        g4 = v7;
                        g5 = v8;
                        return *(int32_t *)0x1f04;
                    }
                    // 0x1e90
                    v57 = 8 * v15;
                    g12 = v57;
                    v47 = v57 + v11;
                    v72 = *(int32_t *)(v47 + 4);
                    v28 = v63 + 1;
                    v73 = *(int32_t *)v47 + v28;
                    v21 = (int32_t)(v63 == -1) + v22 + v72 + (int32_t)(v73 < v28);
                    *(int32_t *)v34 = v73;
                    *(int32_t *)(v34 + 4) = v21;
                    v25 = v11;
                    v48 = g12 + v25;
                    v64 = g13;
                    v74 = v64 + *(int32_t *)v48;
                    g13 = v74;
                    v80 = g14 + *(int32_t *)(v48 + 4) + (int32_t)(v74 < v64);
                    g14 = v80;
                    v29 = v74 + 1;
                    v31 = v80 + (int32_t)(v74 == -1);
                    v35 = result;
                    if (v29 == v35 && v31 == v20) {
                        // 0x1ed0
                        v36 = g11;
                        v78 = *(int32_t *)(v36 + 28);
                        if (v31 == v78) {
                            // if_1ed8_0_true
                            if (v29 >= *(int32_t *)(v36 + 24)) {
                                // 0x1e0c
                                v43 = 8 * v74 + v25;
                                *(int32_t *)v43 = v29;
                                *(int32_t *)(v43 + 4) = v20;
                                g9 = v1;
                                g10 = v2;
                                g11 = v3;
                                g12 = v4;
                                g13 = v5;
                                g14 = v6;
                                g4 = v7;
                                g5 = v8;
                                return *(int32_t *)0x1f04;
                            }
                        } else {
                            // after_if_1ed8_0
                            if (v31 >= v78) {
                                // 0x1e0c
                                v43 = 8 * v74 + v25;
                                *(int32_t *)v43 = v29;
                                *(int32_t *)(v43 + 4) = v20;
                                g9 = v1;
                                g10 = v2;
                                g11 = v3;
                                g12 = v4;
                                g13 = v5;
                                g14 = v6;
                                g4 = v7;
                                g5 = v8;
                                return *(int32_t *)0x1f04;
                            }
                        }
                        // 0x1ee0
                        result3 = 8 * v29;
                        v26 = v73;
                        v30 = v26 + 1;
                        g9 = v30;
                        v32 = (int32_t)(v26 == -1) + v21;
                        g10 = v32;
                        v49 = result3 + v25;
                        v58 = *(int32_t *)v49;
                        v75 = *(int32_t *)(v49 + 4);
                        v76 = v58 + v30;
                        v37 = v19;
                        *(int32_t *)v37 = v76;
                        *(int32_t *)(v37 + 4) = v75 + v32 + (int32_t)(v76 < v58);
                        up();
                        return result3;
                    }
                    // 0x1e0c
                    v43 = 8 * v74 + v25;
                    *(int32_t *)v43 = v35;
                    *(int32_t *)(v43 + 4) = v20;
                    g9 = v1;
                    g10 = v2;
                    g11 = v3;
                    g12 = v4;
                    g13 = v5;
                    g14 = v6;
                    g4 = v7;
                    g5 = v8;
                    return *(int32_t *)0x1f04;
                }
            }
            // 0x1da4
            v61 = v66;
            v59 = v52;
            // branch -> 0x1dac
        }
    } else {
        // 0x1d88
        v50 = 8 * v12;
        g4 = v50;
        result = v12;
        v20 = v13;
        v38 = v50 + v11;
        v34 = v38;
        v60 = v12;
        v63 = *(int32_t *)v38;
        v22 = *(int32_t *)(v38 + 4);
        // branch -> 0x1dd4
    }
    // 0x1dd4
    v67 = v63 + v60;
    if (v67 + 1 == v15 && v22 + v13 + (int32_t)(v67 < v60) + (int32_t)(v67 == -1) == v16) {
        // 0x1e90
        v57 = 8 * v15;
        g12 = v57;
        v47 = v57 + v11;
        v72 = *(int32_t *)(v47 + 4);
        v28 = v63 + 1;
        v73 = *(int32_t *)v47 + v28;
        v21 = (int32_t)(v63 == -1) + v22 + v72 + (int32_t)(v73 < v28);
        *(int32_t *)v34 = v73;
        *(int32_t *)(v34 + 4) = v21;
        v25 = v11;
        v48 = g12 + v25;
        v64 = g13;
        v74 = v64 + *(int32_t *)v48;
        g13 = v74;
        v80 = g14 + *(int32_t *)(v48 + 4) + (int32_t)(v74 < v64);
        g14 = v80;
        v29 = v74 + 1;
        v31 = v80 + (int32_t)(v74 == -1);
        v35 = result;
        if (v29 == v35 && v31 == v20) {
            // 0x1ed0
            v36 = g11;
            v78 = *(int32_t *)(v36 + 28);
            if (v31 == v78) {
                // if_1ed8_0_true
                if (v29 >= *(int32_t *)(v36 + 24)) {
                    // 0x1e0c
                    v43 = 8 * v74 + v25;
                    *(int32_t *)v43 = v29;
                    *(int32_t *)(v43 + 4) = v20;
                    g9 = v1;
                    g10 = v2;
                    g11 = v3;
                    g12 = v4;
                    g13 = v5;
                    g14 = v6;
                    g4 = v7;
                    g5 = v8;
                    return *(int32_t *)0x1f04;
                }
            } else {
                // after_if_1ed8_0
                if (v31 >= v78) {
                    // 0x1e0c
                    v43 = 8 * v74 + v25;
                    *(int32_t *)v43 = v29;
                    *(int32_t *)(v43 + 4) = v20;
                    g9 = v1;
                    g10 = v2;
                    g11 = v3;
                    g12 = v4;
                    g13 = v5;
                    g14 = v6;
                    g4 = v7;
                    g5 = v8;
                    return *(int32_t *)0x1f04;
                }
            }
            // 0x1ee0
            result3 = 8 * v29;
            v26 = v73;
            v30 = v26 + 1;
            g9 = v30;
            v32 = (int32_t)(v26 == -1) + v21;
            g10 = v32;
            v49 = result3 + v25;
            v58 = *(int32_t *)v49;
            v75 = *(int32_t *)(v49 + 4);
            v76 = v58 + v30;
            v37 = v38;
            *(int32_t *)v37 = v76;
            *(int32_t *)(v37 + 4) = v75 + v32 + (int32_t)(v76 < v58);
            up();
            return result3;
        }
        v53 = v35;
        v24 = v25;
        v42 = v74;
    } else {
        // 0x1df4
        v41 = 8 * v67 + v11;
        *(int32_t *)v41 = v15;
        *(int32_t *)(v41 + 4) = g14;
        v23 = v11;
        v53 = result;
        v24 = v23;
        v42 = g13 + *(int32_t *)(v23 + 8 * v15);
        // branch -> 0x1e0c
    }
    // 0x1e0c
    v43 = 8 * v42 + v24;
    *(int32_t *)v43 = v53;
    *(int32_t *)(v43 + 4) = v20;
    g9 = v1;
    g10 = v2;
    g11 = v3;
    g12 = v4;
    g13 = v5;
    g14 = v6;
    g4 = v7;
    g5 = v8;
    return *(int32_t *)0x1f04;
}

// Address range: 0x1f08 - 0x1f27
int32_t kteec_get_revision(int32_t a1, int32_t a2) {
    // 0x1f08
    g3 = a2;
    int32_t v1 = g1; // 0x1f14
    g1 = 0x1f1c;
    g2 = 0;
    g5 = v1;
    ((int32_t (*)(int32_t, int32_t))g6)(0, a2);
    return 0;
}

// Address range: 0x1f28 - 0x1f3b
int32_t function_1f28(void) {
    // 0x1f28
    return unknown_3600();
}

// Address range: 0x1f3c - 0x1f4f
int32_t cleanup_module(void) {
    // 0x1f3c
    return unknown_384c();
}

// --------------- Dynamically Linked Functions ---------------

// void kthread_should_stop(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5);
// void mutex_unlock(void);
// void up(void);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (4.7.3)
// Detected functions: 20
// Decompiler release: v2.2.1 (2016-09-07)
// Decompilation date: 2018-03-05 07:17:09
