#!/bin/sh

#put this file into /etc/ifplugd/

case "$2" in
up)
	echo "1" > /nvtpipe/linkstat
	;;
down)
	echo "0" > /nvtpipe/linkstat
	;;
*)
	echo "ifplugd.action: Incorrect action argument" >&2
	exit 1
	;;
esac
