var all_country = ["Australia","Austria","Belgium","Bulgaria","Croatia","Czech","Denmark","Finland","France","Germany",
			    "Greece","Hungary","Italy","Luxembourg","Netherland","Norway","Poland","Portugal","Rumania","Russia",
			    "Serbia","Slovenia","Spain","Sweden","Switzerland","UK","New Zealand","Arab","Estonia","Hebrew",
				"Latvia","Slovakia","Turkey","Ireland","Japan","Philippines","Thailand","Maldives","Uruguay","Peru",
				"Argentina","Chile","Venezuela","Ecuador","Costarica","Paraguay","Bolivia","Belize","Nicaragua","Guatemala",
				"China","Taiwan","Brazil","Canada","Mexico","United States","South Korea","Others","Lithuania"/*新添加的，底层结构体中没有*/,"Ukraine"/*新添加的，底层结构体中没有*/];
				
var all_language =["Czech","Chamic","Danish","Dargwa","Landdayak","German","English","Spanish","Greek","French",
				"Croatian","Sorbianupper","Italian","Hungarian","Dutch","Norwegian","Polish","Portuguese","Russian","Romanian",
				"Slovenian","Serbian","Finnish","Swedish","Bulgarian","Slovak","Chinese","Chuukese","Gaelic","Gbaya",
				"Welsh","Arabic","Irish","Latvian","Hebrew","Turkish","Estonian","Netherlands","Korean","Kosraean",
				"Hindi","Hittite","Hmong","Mandarin","Cantonese","Maori","Qaa","Undetermined","Ad","Unknown",
				"None","Abkhazian","Achinese","Acoli","Adangme","Adyghe","Afar","Afrihili","Afrikaans","Afro",
				"Ainu","Akan","Akkadian","Albanian","Aleut","Algonquian","Altaisouthern","Altaic","Amharic","Apache",
				"Aramaic","Aragonese","Arapaho","Araucanian","Arawak","Armenian","Artificial","Assamese","Asturian","Athapascan",
				"Austronesian","Australian","Avaric","Avestan","Awadhi","Aymara","Azerbaijani","Aztec","Balinese","Baltic",
				"Baluchi","Bambara","Bamileke","Banda","Bantu","Basa","Bashkir","Basque","Beja","Bemba",
				"Bengali","Berber","Bhojpuri","Bihari","Bikol","Bini","Bislama","Bosnian","Braj","Breton",
				"Buginese","Buriat","Burmese","Blin","Byelorussian","Caddo","Carib","Catalan","Caucasian","Cebuano",
				"Celtic","Centralamericanindian","Chagatai","Chamorro","Chechen","Cherokee","Cheyenne","Chibcha","Chinookjargon","Choctaw",
				"Chipewyan","Churchslavic","Chuvash","Coptic","Cornish","Corsican","Cree","Creek","Creolesandpidgins","Crimeantatar",
				"Creolesandpidginsenglish","Creolesandpidginsfrench","Creolesandpidginsportuguese","Kashubian","Cushitic","Dakota","Delaware","Slavey","Dogrib","Dhivehi",
				"Dinka","Divehi","Dogri","Dravidian","Sorbianlower","Duala","Dutchmiddle","Dyula","Dzongkha","Efik",
				"Egyptian","Ekajuk","Elamite","Englishmiddle","Englishold","Angika","Eskimo","Esperanto","Ewe","Ewondo",
				"Fang","Fanti","Faroese","Fijian","Filipino","Finnougrian","Fon","Frenchmiddle","Frenchold","Frisiannorthern",
				"Frisianeastern","Frisian","Fulah","Friulian","Ga","Gallegan","Ganda","Gayo","Geez","Georgian",
				"Germanmiddlehigh","Germanoldhigh","Gorontalo","Germanic","Gilbertese","Gondi","Gothic","Grebo","Greekancient","Greenlandic",
				"Guarani","Swissgerman","Gujarati","Gwichin","Haida","Haitiancreole","Hausa","Hawaiian","Herero","Hiligaynon",
				"Himachali","Hirimotu","Hupa","Iban","Icelandic","Ido","Nuosu","Igbo","Ijo","Iloko",
				"Indic","Indoeuropean","Ingush","Indonesian","Interlingua","Interlingue","Inuktitut","Inupiak","Iranian","Irishold",
				"Irishmiddle","Iroquoian","Japanese","Javanese","Lojban","Judeoarabic","Judeopersian","Kabyle","Kachin","Kamba",
				"Kannada","Kanuri","Karakalpak","Karen","Kashmiri","Kawi","Kazakh","Circassian","Khasi","Khmer",
				"Khoisan","Khotanese","Kikuyu","Kinyarwanda","Kirghiz","Kimbundu","Komi","Kongo","Konkani","Kpelle",
				"Karachaybalkar","Karelian","Kru","Kuanyama","Kumyk","Kurdish","Kurukh","Kusaie","Kutenai","Ladino",
				"Lahnda","Lamba","Langue","Lao","Latin","Letzeburgesch","Lezghian","Limburgish","Lingala","Lithuanian",
				"Lozi","Lubalulua","Lubakatanga","Luiseno","Lunda","Luo","Lushai","Macedonian","Madurese","Magahi",
				"Maithili","Makasar","Malagasy","Malay","Moksha","Mandar","Malayalam","Maltese","Manchu","Mandingo",
				"Manipuri","Manobo","Manx","Marathi","Mari","Marshall","Mirandese","Marwari","Masai","Mayan",
				"Erzya","Mende","Micmac","Minangkabau","Miscellaneous","Mohawk","Moldavian","Monkmer","Mongo","Mongolian",
				"Mossi","Multiple","Munda","Neapolitan","Nauru","Navajo","Ndebelenorth","Ndebelesouth","Ndongo","Germanlow",
				"Nepali","Newari","Nias","Nigerkordofanian","Nilosaharan","Niuean","Norwegianbokmal","Nogai","Norseold","Northamericanindian",
				"Norwegiannynorsk","Nubian","Nyamwezi","Newariclassical","Nyanja","Nyankole","Nyoro","Nzima","Ojibwa","Oriya",
				"Oromo","Osage","Ossetic","Otomian","Pahlavi","Palauan","Pali","Pampanga","Pangasinan","Panjabi",
				"Papiamento","Papuanaustralian","Persian","Persianold","Phoenician","Philippine","Ponape","Prakrit","Provencalold","Pushto",
				"Quechua","Rhaetoromance","Rajasthani","Rapanui","Rarotongan","Romance","Romany","Rundi","Aromanian","Salishan",
				"Samaritanaramaic","Samisouthern","Saminorthern","Sami","Lulesami","Inarisami","Samoan","Skoltsami","Sandawe","Sango",
				"Sanskrit","Sardinian","Sasak","Santali","Sicilian","Scots","Selkup","Semitic","Sranantongo","Serbocroatian",
				"Serer","Sign","Shan","Shona","Sidamo","Siksika","Sindhi","Soninke","Singhalese","Sinotibetan",
				"Siouan","Slavic","Siswant","Sogdian","Somali","Songhai","Sorbian","Walloon","Nko","Sothonorthern",
				"Sothosouthern","Southamericanindian","Sukuma","Sumerian","Sudanese","Susu","Swahili","Swazi","Swize","Syriacclassical",
				"Syriac","Tagalog","Tahitian","Tetum","Tajik","Tamashek","Tai","Tamil","Tatar","Teletext",
				"Telugu","Tereno","Thai","Tibetan","Tigre","Tigrinya","Timne","Tivi","Klingon","Tokelau",
				"Tlingit","Tonganyasa","Tongaislands","Truk","Tokpisin","Tsimshian","Tsonga","Tswana","Tumbuka","Tupian",
				"Turkishottoman","Turkmen","Tuvinian","Tuvalu","Twi","Udmurt","Ugaritic","Uighur","Ukrainian","Umbundu",
				"Urdu","Uzbek","Vai","Venda","Vietnamese","Volapuk","Votic","Wakashan","Walamo","Waray",
				"Washo","Wolof","Kalmyk","Xhosa","Yakut","Yao","Yap","Yiddish","Yoruba","Yupik",
				"Zapotec","Blissymbolics","Zenaga","Zhuang","Zande","Zulu","Zuni","Zazaki","Valencian","Num"];